# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74241f6a1ea4bcf1e319133f6217ce3cbb8df8b40269ac34467bb03420fadd08aae71e261cde758023376b9097e50482e83497c2a25def9d7c9e7d75b53cdd08

test:
  secret_key_base: 82d28f6d6edd3a587d84e80d78725a0ee60632887a17870aa3e822d4fd378e8f08848995e1e66a68493e843d5cfe9b4576379fba5a3aa231c993ada9a67430d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
